#!/usr/bin/env bash
#
# Regenerate nginx_url.c by extracting the URL-parsing regions VERBATIM from an
# official nginx release fetched from nginx.org.
#
# This crate is developed independently of the nginx tree: the reference nginx
# source is downloaded on demand (pinned version + sha256), never assumed to
# live in a parent directory. The generated nginx_url.c is committed (vendored)
# so that the fuzzer builds offline; CI re-runs this script and checks that the
# committed file is unchanged (see `make verify`).
#
# Usage:
#   ./tools/extract.sh                 # fetch pinned nginx, regenerate
#   NGINX_VERSION=1.31.1 ./tools/extract.sh
#   NGINX_TARBALL=/path/to/nginx.tar.gz ./tools/extract.sh   # use local file
#
set -euo pipefail

NGINX_VERSION="${NGINX_VERSION:-1.31.1}"
# sha256 of nginx-${NGINX_VERSION}.tar.gz from nginx.org. Update when bumping.
NGINX_SHA256="${NGINX_SHA256:-9fcaaeb8f22544b09a19a761f3412c4112215422401634bebdd1296a403cc4bc}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$HERE/nginx_url.c"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- obtain the nginx source tarball ---
tarball="$WORK/nginx.tar.gz"
if [[ -n "${NGINX_TARBALL:-}" ]]; then
    echo "using local tarball: $NGINX_TARBALL"
    cp "$NGINX_TARBALL" "$tarball"
else
    url="https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"
    echo "downloading $url"
    curl -fsSL -o "$tarball" "$url"
fi

echo "verifying sha256"
echo "${NGINX_SHA256}  ${tarball}" | sha256sum -c -

tar -xzf "$tarball" -C "$WORK"
SRC="$WORK/nginx-${NGINX_VERSION}/src/http/ngx_http_parse.c"
[[ -f "$SRC" ]] || { echo "error: $SRC not found in tarball" >&2; exit 1; }

# --- pattern-based extraction (robust to line-number drift across versions) ---

# usual[] table: from its declaration through the closing "};".
extract_usual() {
    awk '
        /^static uint32_t  usual\[\] = \{/ { c = 1 }
        c { print }
        c && /^};/ { exit }
    ' "$SRC"
}

# A top-level function definition: the return-type line + signature line through
# the first column-0 "}" (nginx style puts the closing brace at column 0).
extract_fn() {
    awk -v name="$1" '
        $0 ~ ("^" name "\\(") { print prev; c = 1 }
        c { print }
        c && /^}/ { exit }
        { prev = $0 }
    ' "$SRC"
}

# sanity: make sure each region was found and is non-trivial
check_nonempty() { [[ "$(wc -l <<<"$1")" -ge 5 ]] || { echo "error: extraction of '$2' failed" >&2; exit 1; }; }

USUAL="$(extract_usual)";                            check_nonempty "$USUAL" "usual[]"
PARSE_URI="$(extract_fn ngx_http_parse_uri)";        check_nonempty "$PARSE_URI" "ngx_http_parse_uri"
COMPLEX="$(extract_fn ngx_http_parse_complex_uri)";  check_nonempty "$COMPLEX" "ngx_http_parse_complex_uri"

# --- assemble nginx_url.c ---
cat > "$OUT" <<HEAD
/*
 * URL-path normalization fuzz harness for nginx.
 *
 * GENERATED by tools/extract.sh from nginx ${NGINX_VERSION} (nginx.org).
 * Do NOT edit the extracted regions by hand; re-run tools/extract.sh instead.
 *
 * The extracted regions below are VERBATIM from src/http/ngx_http_parse.c and
 * are covered by the nginx license:
 *
 *   Copyright (C) Igor Sysoev
 *   Copyright (C) Nginx, Inc.
 *   (2-clause BSD; see https://nginx.org/LICENSE)
 *
 * Contains, verbatim:
 *   - usual[]                     (the "ordinary character" bitmap)
 *   - ngx_http_parse_uri()        (stage 1: origin-form flag/boundary setter)
 *   - ngx_http_parse_complex_uri()(stage 2: the actual path normalizer)
 * plus a small wrapper that reproduces the Linux path of
 * ngx_http_process_request_uri() and exposes a C ABI for Rust FFI.
 */

#include "ngx_stub.h"

/* ==== BEGIN verbatim: usual[] (ngx_http_parse.c) ==================== */
HEAD

printf '%s\n' "$USUAL" >> "$OUT"

cat >> "$OUT" <<'MID1'
/* ==== END verbatim: usual[] ======================================== */


/* ==== BEGIN verbatim: ngx_http_parse_uri() ========================= */
MID1

printf '%s\n' "$PARSE_URI" >> "$OUT"

cat >> "$OUT" <<'MID2'
/* ==== END verbatim: ngx_http_parse_uri() =========================== */


/* ==== BEGIN verbatim: ngx_http_parse_complex_uri() ================= */
MID2

printf '%s\n' "$COMPLEX" >> "$OUT"

cat >> "$OUT" <<'TAIL'
/* ==== END verbatim: ngx_http_parse_complex_uri() =================== */


/* ==== BEGIN authored wrapper ======================================= */
/*
 * nginx_parse_path_and_query: parse one origin-form target exactly as nginx
 * does.
 *
 *   in, in_len     raw request-target bytes (need NOT be NUL-terminated)
 *   merge_slashes  fuzzer input: 1 = collapse "//" (nginx default), 0 = keep
 *   out            caller buffer; must have capacity >= in_len + 1
 *   out_cap        capacity of out
 *   out_len        set to the normalized path length on success
 *   args_offset     set to the query-string offset in in on success
 *   args_len        set to the query-string length on success
 *   args_present    set to 1 when query arguments are present, otherwise 0
 *
 * returns:
 *    0  success (out[0..*out_len) is the normalized path; when *args_present
 *       is 1, in[*args_offset..*args_offset + *args_len) is the query string)
 *   -1  nginx rejected the request target (parse error / invalid request)
 *   -2  out_cap too small (should never happen if out_cap >= in_len + 1)
 *
 * Faithfulness notes:
 *   - parse_complex_uri reads ONE byte at *uri_end (and discards it), matching
 *     nginx's "there is always a LF after the URI" invariant. We copy the
 *     input into a len+1 buffer with a trailing '\n' so that read is always
 *     valid regardless of what the caller's slice guarantees.
 *   - Normalization only shrinks or keeps length (%XX -> 1 byte, "."/".."/"//"
 *     removal), so out never needs more than in_len bytes; +1 covers the
 *     (origin-form-unreachable) empty_path leading-slash case for parity.
 *   - The "simple URI" branch returns the input path unchanged, exactly as
 *     ngx_http_process_request_uri() does when no flag is set.
 *   - Query arguments always refer to the original input, so returning their
 *     offset and length requires no additional buffer or allocation.
 */
int
nginx_parse_path_and_query(const unsigned char *in, size_t in_len,
                           int merge_slashes,
                           unsigned char *out, size_t out_cap, size_t *out_len,
                           size_t *args_offset, size_t *args_len,
                           int *args_present)
{
    ngx_http_request_t  r;
    u_char             *inbuf, *nbuf;
    int                 rc = 0;

    memset(&r, 0, sizeof(r));

    inbuf = (u_char *) malloc(in_len + 1);
    nbuf  = (u_char *) malloc(in_len + 1);
    if (inbuf == NULL || nbuf == NULL) {
        free(inbuf);
        free(nbuf);
        return -1;
    }

    if (in_len) {
        memcpy(inbuf, in, in_len);
    }
    inbuf[in_len] = '\n';   /* nginx invariant: a LF follows the URI */

    r.uri_start = inbuf;
    r.uri_end   = inbuf + in_len;

    /* stage 1: origin-form parse (sets complex_uri/quoted_uri/args_start/...) */
    if (ngx_http_parse_uri(&r) != NGX_OK) {
        rc = -1;
        goto done;
    }

    /* reproduce the Linux path of ngx_http_process_request_uri() */
    if (r.args_start) {
        r.uri.len = (size_t) (r.args_start - 1 - r.uri_start);
    } else {
        r.uri.len = (size_t) (r.uri_end - r.uri_start);
    }

    if (r.complex_uri || r.quoted_uri || r.empty_path_in_uri) {
        if (r.empty_path_in_uri) {
            r.uri.len++;
        }
        r.uri.data = nbuf;

        if (ngx_http_parse_complex_uri(&r, merge_slashes ? 1 : 0) != NGX_OK) {
            rc = -1;
            goto done;
        }
    } else {
        r.uri.data = r.uri_start;   /* no normalization needed */
    }

    if (r.args_start && r.uri_end > r.args_start) {
        r.args.len = (size_t) (r.uri_end - r.args_start);
        r.args.data = r.args_start;
    }

    if (r.uri.len > out_cap) {
        rc = -2;
        goto done;
    }

    if (r.uri.len) {
        memcpy(out, r.uri.data, r.uri.len);
    }
    *out_len = r.uri.len;

    if (r.args.data) {
        *args_offset = (size_t) (r.args.data - inbuf);
        *args_len = r.args.len;
        *args_present = 1;
    } else {
        *args_offset = 0;
        *args_len = 0;
        *args_present = 0;
    }

done:
    free(inbuf);
    free(nbuf);
    return rc;
}
/* ==== END authored wrapper ========================================= */
TAIL

echo "Regenerated $OUT from nginx ${NGINX_VERSION} ($(wc -l < "$OUT") lines)"
